export const GET_MOVEI_START = "GET_MOVEI_START";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";

export const GET_MOVEI_BY_ID_START = "GET_MOVEI_ACTOR_START";
export const GET_MOVEI_BY_ID_SUCCESS = "GET_MOVEI_ACTOR_SUCCESS";
export const GET_MOVEI_BY_ID_FAILED = "GET_MOVEI_ACTOR_FAILED";

